require: rubocop-rails

AllCops:
  Exclude:
    - "db/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "app/channels/**/*"
    - "bin/*"
    - "config/**/*"
    - "test/**/*"
    - "Rakefile"
    - "config.ru"
Style/ClassAndModuleChildren:
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # The compact style is only forced, for classes / modules with one child.
  EnforcedStyle: compact
Style/EachWithObject:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Enabled: true
# Prefer :sym => value syntax
Style/HashSyntax:
  EnforcedStyle: ruby19
  Enabled: true
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  Enabled: true
Style/Documentation:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
Style/MutableConstant:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 8
Style/Lambda:
  Enabled: false
Metrics/LineLength:
  Max: 140
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 25
  Enabled: false
Metrics/MethodLength:
  Max: 25
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 50
